### ISSUE TITLE
US 01.07.01 Rider: Complete a Request

### ISSUE THREAD

**Issue by DulongSang** [CMPUT301W20T29-H03/ZoomWroom#103]

**Comment by DulongSang** [comment]
Almost done, need some help.
I do not know how to test a BottomSheetFragment, and I do not know what should the program do after the user (rider) click the complete button.

**Comment by heyitshenrylin** [comment]
@DulongSang 

The rider clicks the complete button, and then waits for the driver to click the complete button as well.

Then when they both have a "completed" state, the driver's phone should start the qr scanner activity, while the rider should get a qr code generated

**Comment by DulongSang** [comment]
![](https://github.com/CMPUT301W20T29-H03/ZoomWroom/blob/master/doc/Images/ui-mockup/UserComplete.png)

**Comment by heyitshenrylin** [comment]
Amanda can help with the complete button

**Comment by amandanguyeen** [comment]
Dulong: recreating the completed fragment, remove the "generate QR code" fragment
Amanda: have the generated QR code pop up then Dulong's completed fragment
