### ISSUE TITLE
Create Entity Classes

### ISSUE THREAD

**Issue by sharyar** [CMPUT301W20T29-H03/ZoomWroom#12]
- [x] User
- [x] Rider
- [x] Driver
- [x] Contact information
- [x] Password
- [x] QRBucks
- [x] Rating
- [x] Location
- [x] RideStatus
- [x] Notification
- [x] DatabaseHelper

**Comment by DulongSang** [comment]
Problem: I think we do not need a separate Image class, we should just use android Drawable class instead. We can use Drawable.createFromPath(String path) to load images.

**Comment by sharyar** [comment]
Please note that the image class has been removed from her.
