### ISSUE TITLE
Memory Leak in Database class

### ISSUE THREAD

**Issue by sharyar** [CMPUT301W20T29-H03/ZoomWroom#147]
Found a memory leak in the my database class. 

Essentially, when I ran a code analysis on our app, I found this one being a huge issue and possibly causing a lot of the lag we are seeing in the app. 

Warning:(25, 13) Do not place Android context classes in static fields (static reference to `FirebaseFirestore` which has field `context` pointing to `Context`); this is a memory leak

Code in question is on link 25 of MyDatabase:

private static FirebaseFirestore db = FirebaseFirestore.getInstance();

**Comment by sharyar** [comment]
@lsykanade I believe you originally worked on this, any way to refactor this to avoid the memory leak?

**Comment by heyitshenrylin** [comment]
@lsykanade @sharyar Again, if the static field is used because you need an existing instance of FirebaseFirestore please use the singleton methods we described in class

**Comment by lsykanade** [comment]
I understand. I am going to make it a singleton

**Comment by DulongSang** [comment]
#173
