### ISSUE TITLE
Driver clicking on Rider name crashes app

### ISSUE THREAD

**Issue by heyitshenrylin** [CMPUT301W20T29-H03/ZoomWroom#159]
Null object reference on getUsername due to MyDatabase.getRider(userID) returns 0, however the firebase db has the rider in it.

**Comment by heyitshenrylin** [comment]
@lsykanade has also said that the getRider method has also broken in DriverHomeActivity

**Comment by DulongSang** [comment]
Are you working on it? I think I can change the activity to a DialogFragment and also solve issue #156

**Comment by heyitshenrylin** [comment]
@DulongSang It seems to have fixed itself after clearing all app data, please go ahead but keep this issue open in case someone else finds this problem
