### ISSUE TITLE
edit user profile check validity issue

### ISSUE THREAD

**Issue by DulongSang** [CMPUT301W20T29-H03/ZoomWroom#161]
The user cannot change the username even if it is unique.

**Comment by DulongSang** [comment]
Encountered this problem:
`I/Choreographer: Skipped 64 frames!  The application may be doing too much work on its main thread.`
at line 116 - 139 in EditUserProfileActivity.java
I cannot locate exactly where the problem is.

There is a logic error in line 128, it should be `!MyDataBase.isUserNameUnique(newUserName)`
But this might not be the reason why the app does not work.

**Comment by DulongSang** [comment]
This problem happens if:
modify the code in line 128 to `if (!MyDataBase.isUserNameUnique(newUserName)) {`,
then, in the app, change the username.

**Comment by sharyar** [comment]
@DulongSang I will have a look

**Comment by sharyar** [comment]
@DulongSang it looks like this method takes too long so it will have to be done by Asynctask which I don't know how to do and I don't think I can work on that while also doing qrbucks stuff.

**Comment by DulongSang** [comment]
I am trying to fix it, hopefully I can fix it.

**Comment by sharyar** [comment]
Try this: 

Create an inner class within mydatabase specifically for the isUserNameUnique function. Use asyn task as per this tutorial: https://stackoverflow.com/questions/14250989/how-to-use-asynctask-correctly-in-android

I will give it a shot too later if I can.
