### ISSUE TITLE
Can't see QRBucks in list

### ISSUE THREAD

**Issue by sharyar** [CMPUT301W20T29-H03/ZoomWroom#182]
QR Bucks do not appear in the QRBucks screen. 

@heyitshenrylin can you provide me with the login info for the driver you used?

**Comment by sharyar** [comment]
I believe this has to do with the duplicate QR Bucks.

**Comment by heyitshenrylin** [comment]
@sharyar I've figured out a quick fix that would work well, but not optimally.

I've been unable to figure out how to reliably send only 1 request from the qr scanner, it seems to always create 2 QR bucks.

The quick fix I've been able to make is to just show all qrbucks associated to a driver but then just remove duplicate driverequests
