### ISSUE TITLE
Implement Driver Homepage

### ISSUE THREAD

**Issue by heyitshenrylin** [CMPUT301W20T29-H03/ZoomWroom#39]
- [ ] Get ride requests from firebase db
- [x] Display requests as markers on map
- [x] Implement onclick for each marker to display fragment containing
   - Rider clickable profile
   - Ride request departure and destination markers
   - Centering map where driver can see their current location, as well as the start and end locations for the trip
- [x] Send accept ride request to firebase db

**Comment by heyitshenrylin** [comment]
I will be working on getting a working map for the drivers, please figure out how to get ride requests from the database and send accept ride requests to database beforehand and I'll get the driver map working

**Comment by sharyar** [comment]
Currently working on this. Just waiting for firebase to be setup for riderequests.
