### ISSUE TITLE
Implement GeoCode & Reverse Geocode in Driverhome page and RiderHome Page

### ISSUE THREAD

**Issue by sharyar** [CMPUT301W20T29-H03/ZoomWroom#46]
This allows the app to display the address if the user picks it on the map. It also updates the maker if the user updates the address on the text field. 

This is also used to display the address to the drivers when they pick requests. 

Here is a good tutorial: https://www.journaldev.com/15676/android-geocoder-reverse-geocoding

**Comment by heyitshenrylin** [comment]
Not needed as per user stories
