### ISSUE TITLE
User Profile Display after Editing

### ISSUE THREAD

**Issue by DulongSang** [CMPUT301W20T29-H03/ZoomWroom#89]
*This is NOT important*
After editing the user profile in EditProfile activity and clicking the confirm button, the activity will return to the UserProfileActivity. And the user profile should display the updated profile info. But actually it does not. I found that it might be because the firebase does not update immediately, and the UserProfileActivity retrieves the data before updating. (You can try to go to another activity and go back to the userprofile activity, and you can see the changes)

**Comment by DulongSang** [comment]
The display update happens in the onResume() method, so it should update the display info every time you return to (or create) this activity.

**Comment by sharyar** [comment]
Is this completed?

**Comment by DulongSang** [comment]
Not yet, but I came up with an idea that might work and I will try to solve that as soon as possible.
